version: "3.7"
services:
  explorer:
    image: explorer
    ports:
      - "3000:3000"
    environment:
      - "NEXT_PUBLIC_MAINNET_API_SERVER=https://stacks-node-api.alexlab.co"
      - "NEXT_PUBLIC_TESTNET_API_SERVER=https://stacks-node-api.alexgo.dev"
      - "NEXT_PUBLIC_LEGACY_EXPLORER_API_SERVER=https://explorer-api.legacy.blockstack.org"
      - "NEXT_PUBLIC_DEPLOYMENT_URL=http://localhost:3000"
      - "NEXT_PUBLIC_MAINNET_ENABLED=true"
      - "NEXT_PUBLIC_DEFAULT_POLLING_INTERVAL=10000"
